#!/usr/bin/env python3
"""Generate the reference-oct transition lifts in gpu/gpu_implicit_tables.f90."""

from itertools import product
from pathlib import Path

import numpy as np


def reference_complex():
    """Section 4 local orders, incidences, and section 5 boundary lifts."""
    vertices = list(product(range(3), repeat=3))
    vi = {p: i for i, p in enumerate(vertices)}
    edges, faces = [], []
    for a in range(3):
        others = [d for d in range(3) if d != a]
        for i, j, k in product(range(2), range(3), range(3)):
            p = [0, 0, 0]
            p[a], p[others[0]], p[others[1]] = i, j, k
            edges.append((a, tuple(p)))
        b, c = (a+1) % 3, (a+2) % 3
        for i, j, k in product(range(3), range(2), range(2)):
            p = [0, 0, 0]
            p[a], p[b], p[c] = i, j, k
            faces.append((a, tuple(p)))
    ei = {key: i for i, key in enumerate(edges)}
    G, C = np.zeros((54, 27), dtype=int), np.zeros((36, 54), dtype=int)
    for e, (a, p) in enumerate(edges):
        q = list(p)
        q[a] += 1
        G[e, vi[p]], G[e, vi[tuple(q)]] = -1, 1
    for f, (a, p) in enumerate(faces):
        b, c = (a+1) % 3, (a+2) % 3
        q, r = list(p), list(p)
        q[b] += 1
        r[c] += 1
        for key, sign in (((b, p), 1), ((c, tuple(q)), 1),
                          ((b, tuple(r)), -1), ((c, p), -1)):
            C[f, ei[key]] = sign
    bf = np.array([f for f, (a, p) in enumerate(faces) if p[a] in (0, 2)])
    be = np.array([e for e, (a, p) in enumerate(edges)
                   if any(p[d] in (0, 2) for d in range(3) if d != a)])
    bv = np.array([v for v, p in enumerate(vertices) if any(t in (0, 2) for t in p)])
    centres = [vi[tuple(2*side if d == a else 1 for d in range(3))]
               for a, side in product(range(3), range(2))]
    Cb, Gb = C[np.ix_(bf, be)], G[np.ix_(be, bv)]
    P, Q = np.linalg.pinv(Cb), np.linalg.pinv(Gb)
    lift_f = C[:, be] @ P
    z = P @ Cb
    chi = np.zeros((27, 48))
    chi[bv] = Q @ (np.eye(48)-z)
    chi[vi[(1, 1, 1)]] = np.mean(chi[centres], axis=0)
    lift_e = G @ chi
    lift_e[be] += z
    return dict(vertices=vertices, edges=edges, faces=faces, vi=vi, ei=ei,
                C=C, G=G, bf=bf, be=be, bv=bv, centres=centres,
                lift_f=lift_f, lift_e=lift_e)


def nodal(s):
    return np.array([s*(s-1)/2, 1-s*s, s*(s+1)/2])


def interval_integrals(lo, hi):
    return np.array([(hi-lo-(hi*hi-lo*lo))/2, (hi-lo+(hi*hi-lo*lo))/2])


def restriction(bit, face=False, reference=None):
    """Exact sub-integrals from a parent oct to a child's virtual oct."""
    ref = reference_complex() if reference is None else reference
    records = ref['faces' if face else 'edges']
    R = np.zeros((len(records), len(records)))
    for row, (a, p) in enumerate(records):
        lo = np.array(bit, dtype=float)-1+np.array(p)/2
        coef = [nodal(lo[d]) if ((d == a) == face)
                else interval_integrals(lo[d], lo[d]+0.5) for d in range(3)]
        for col, (b, q) in enumerate(records):
            if b == a:
                R[row, col] = np.prod([coef[d][q[d]] for d in range(3)])
    return R


def fortran_array(name, values):
    """Column blocks keep each constructor below 255 continuation lines."""
    rows, cols = values.shape
    blocks, lines = [], []
    # Three FP64 literals per line; at most 216 data lines per block.
    block_cols = 12
    for start in range(0, cols, block_cols):
        part = values[:, start:start+block_cols]
        block = f'{name}_{start//block_cols+1}'
        blocks.append(block)
        lines.append(f'  real(kind=8), parameter :: {block}({rows},{part.shape[1]}) = reshape([ &')
        flat = part.ravel(order='F')
        for i in range(0, len(flat), 3):
            literals = []
            for x in flat[i:i+3]:
                value = format(float(x), '.17g')
                if 'e' in value:
                    value = value.replace('e', 'd')
                else:
                    value += 'd0'
                literals.append(value)
            ending = ', &' if i+3 < len(flat) else f' ], [{rows},{part.shape[1]}])'
            lines.append('    '+', '.join(literals)+ending)
        lines.append('')
    lines.append('  ! Concatenate consecutive column blocks in Fortran storage order.')
    lines.append(f'  real(kind=8), parameter :: {name}({rows},{cols}) = reshape([ &')
    lines.append('    '+', '.join(blocks)+f' ], [{rows},{cols}])')
    return lines


def main():
    ref = reference_complex()
    lines = ['! Generated by utils/py/implicit_tables.py.', 'module implicit_tables',
             '  implicit none', '  private', '  public :: lift_f, lift_e', '']
    for name in ('lift_f', 'lift_e'):
        lines.extend(fortran_array(name, ref[name]))
        lines.append('')
    lines.append('end module implicit_tables')
    output = Path(__file__).resolve().parents[2]/'gpu/gpu_implicit_tables.f90'
    output.write_text('\n'.join(lines)+'\n')


if __name__ == '__main__':
    main()
